<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Genetic_Algorithm_For_Image_Recreation</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.SVG" Version="25.11.0" />
    <PackageReference Include="ColorMine" Version="1.1.3" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
  </ItemGroup>

</Project>
